#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

polybar main &
polybar secondary &

nitrogen --restore

xkbcomp -w 0 $HOME/.config/moonlander.xkb $DISPLAY
xset r rate 150 38

# Store the dbus session address in case some other program needs it that isn't run in the same dbus session.
# TODO: Which program uses this file? I belive it has something to do with notifications and discord crashing otherwise.
echo $DBUS_SESSION_BUS_ADDRESS > ~/.dbus-session

# Overwrite the mumd dbus session address and start.
# This is a workaround for mumd crashing if it tries to send notifications.
# TODO: This has been an issue with discord as well. Actually fix this on the system.
cat <<EOF > ~/.config/systemd/user/mumd.service.d/local.conf
[Service]
Environment="DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
EOF
# systemctl --user daemon-reload
# systemctl --user restart mumd

# hide mouse pointer if the keyboard is used
xbanish &
# notification daemon.
dunst &
# captures data usage
arbtt-capture &
