- clean: ['~']

- defaults:
    link: 
      create: true

- link:
    ~/.config/fish/config.fish: fish.config.fish
    ~/.gitconfig:
    ~/.ssh/config: ssh-config
    ~/.zshrc:
    ~/.Xresources:
    ~/.xinitrc:
    ~/.config/sxhkd/sxhkdrc: sxhkdrc
    ~/.config/rofi/config.rasi: rofi.config.rasi
    ~/.config/dunst/dunstrc:
