- clean: ['~']

- defaults:
    link: 
      create: true

- link:
    ~/.config/fish/config.fish: config.fish
    ~/.gitconfig:
    ~/.config/sxhkd/sxhkdrc: sxhkdrc
    ~/.ssh/config: ssh/config
    ~/.zshrc:
    ~/.Xresources:
    ~/.xinitrc:
